apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: acme@example.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - selector: {}
        dns01:
          webhook:
            groupName: acme.ukmetrics.ca
            solverName: desec
            config:
              apiTokenSecretRef:
                name: desec-token
                key: token
