apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-example-com
spec:
  secretName: test-example-com-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - test.example.com
