name: Test

on:
  push:

jobs:
  buildx:
    name: Build and push

    runs-on: ubuntu-latest
#    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup Buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64

    # Login
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}

    # Build and push
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
